name: Deploy to npm

on:
  push:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
          cache: "npm"
          registry-url: https://registry.npmjs.org
          scope: "@apparts"

      - name: Get package info
        id: get-local-version
        run: |
          echo "::set-output name=packageName::$(cat package.json | jq .name)"
          echo "::set-output name=packageVersion::$(cat package.json | jq .version)"
      - name: Get npm info
        id: get-npm-published-version
        run: |
          echo "::set-output name=npmVersion::\"$(npm show ${{steps.get-local-version.outputs.packageName}} version)\""
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Print it
        run: |
          echo Local version ${{steps.get-local-version.outputs.packageVersion}}
          echo Remote version ${{steps.get-npm-published-version.outputs.npmVersion}}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish
        if: ${{ steps.get-local-version.outputs.packageVersion != steps.get-npm-published-version.outputs.npmVersion  }}
        name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
